/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiLlmsFullRouteImport } from './routes/api.llms-full'
import { Route as EsDocsSplatRouteImport } from './routes/es.docs.$'
import { Route as EnDocsSplatRouteImport } from './routes/en.docs.$'
import { Route as ApiLlmsPageSplatRouteImport } from './routes/api.llms-page.$'

const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsFullRoute = ApiLlmsFullRouteImport.update({
  id: '/api/llms-full',
  path: '/api/llms-full',
  getParentRoute: () => rootRouteImport,
} as any)
const EsDocsSplatRoute = EsDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => EsRoute,
} as any)
const EnDocsSplatRoute = EnDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => EnRoute,
} as any)
const ApiLlmsPageSplatRoute = ApiLlmsPageSplatRouteImport.update({
  id: '/api/llms-page/$',
  path: '/api/llms-page/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/api/llms-full': typeof ApiLlmsFullRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/llms-page/$': typeof ApiLlmsPageSplatRoute
  '/en/docs/$': typeof EnDocsSplatRoute
  '/es/docs/$': typeof EsDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/api/llms-full': typeof ApiLlmsFullRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/llms-page/$': typeof ApiLlmsPageSplatRoute
  '/en/docs/$': typeof EnDocsSplatRoute
  '/es/docs/$': typeof EsDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/api/llms-full': typeof ApiLlmsFullRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/llms-page/$': typeof ApiLlmsPageSplatRoute
  '/en/docs/$': typeof EnDocsSplatRoute
  '/es/docs/$': typeof EsDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/es'
    | '/api/llms-full'
    | '/api/search'
    | '/docs/$'
    | '/api/llms-page/$'
    | '/en/docs/$'
    | '/es/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/es'
    | '/api/llms-full'
    | '/api/search'
    | '/docs/$'
    | '/api/llms-page/$'
    | '/en/docs/$'
    | '/es/docs/$'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/es'
    | '/api/llms-full'
    | '/api/search'
    | '/docs/$'
    | '/api/llms-page/$'
    | '/en/docs/$'
    | '/es/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRouteWithChildren
  EsRoute: typeof EsRouteWithChildren
  ApiLlmsFullRoute: typeof ApiLlmsFullRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiLlmsPageSplatRoute: typeof ApiLlmsPageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms-full': {
      id: '/api/llms-full'
      path: '/api/llms-full'
      fullPath: '/api/llms-full'
      preLoaderRoute: typeof ApiLlmsFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/docs/$': {
      id: '/es/docs/$'
      path: '/docs/$'
      fullPath: '/es/docs/$'
      preLoaderRoute: typeof EsDocsSplatRouteImport
      parentRoute: typeof EsRoute
    }
    '/en/docs/$': {
      id: '/en/docs/$'
      path: '/docs/$'
      fullPath: '/en/docs/$'
      preLoaderRoute: typeof EnDocsSplatRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/llms-page/$': {
      id: '/api/llms-page/$'
      path: '/api/llms-page/$'
      fullPath: '/api/llms-page/$'
      preLoaderRoute: typeof ApiLlmsPageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnRouteChildren {
  EnDocsSplatRoute: typeof EnDocsSplatRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnDocsSplatRoute: EnDocsSplatRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface EsRouteChildren {
  EsDocsSplatRoute: typeof EsDocsSplatRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsDocsSplatRoute: EsDocsSplatRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRouteWithChildren,
  EsRoute: EsRouteWithChildren,
  ApiLlmsFullRoute: ApiLlmsFullRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiLlmsPageSplatRoute: ApiLlmsPageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
